### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by PedaretKhor** [aytdm/github-playground#10]
go run main.go
2022/08/14 19:24:06 &{0xc0000ca000 0 0 0 0  github.Rate{Limit:60, Remaining:57, Reset:github.Timestamp{2022-08-14 20:18:28 +0430 +0430}}}
2022/08/14 19:24:06 Failed to request issues: %sPOST https://api.github.com/repos/$%7Bowner%7D/$%7Bname%7D/issues: 401 Bad credentials []
exit status 1

**Comment by aytdm** [comment]
> 401 Bad credentials

Authenticating with invalid credentials will return 401. Please check your credentials.
